Models/Agenda.cs
using System.ComponentModel.DataAnnotations.Schema;
using SQLitePCL;

namespace TattooStudioBooking;

public class Agenda
{
    public int Id { get; set; }
    public Artista Artista { get; set; }
    public PuestoTrabajo PuestoTrabajo { get; set; }
    public DateTime FechaReserva { get; set; }
    public int HoraDesde { get; set; }
    public int HoraHasta { get; set; }

    public Agenda()
    {
        this.Artista = new Artista();
        this.PuestoTrabajo = new PuestoTrabajo();
    }


}

Controllers/AgendaController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TattooStudioBooking.Models;
namespace TattooStudioBooking;

public class AgendaController : Controller
{
    private readonly ILogger<AgendaController> _logger;
    private readonly BookingContext _context;

    public AgendaController(ILogger<AgendaController> logger, BookingContext context)
    {
        _logger = logger;
        this._context = context;
    }

    [Authorize]
    public IActionResult Index(int ptoId, int semanaIdx = 0)
    {
        return View(ObtenerReservas(ptoId, semanaIdx));
    }
    [Authorize]
    public IActionResult RegistrarAgenda(int ptoId, int semanaIdx = 0)
    {
        return View("Index", ObtenerReservas(ptoId, semanaIdx));
    }
    [HttpPost]
    [Authorize(Roles = "Artista")]
    public async Task<IActionResult> RegistrarAgenda(int ptoId, int semanaIdx, CrearReserva reserva)// int HoraDesde, int HoraHasta, string Usuario)
    {
        if (ModelState.IsValid)
        {
            if (User.Identity == null || User.Identity.Name != reserva.Usuario)
            {
                ModelState.AddModelError("", "No se encontro user logeado");
                return View("Index", ObtenerReservas(ptoId, semanaIdx));
            }

            Artista? artista = _context.Artistas.FirstOrDefault(x => x.UserName == reserva.Usuario);
            PuestoTrabajo? puestoTrabajo = _context.PuestosTrabajo.FirstOrDefault(x => x.Id == ptoId);

            if (artista == null)
            {
                ModelState.AddModelError("", $"No se encontro user {reserva.Usuario}");
                return View("Index", ObtenerReservas(ptoId, semanaIdx));
            }
            if (puestoTrabajo == null)
            {
                ModelState.AddModelError("", $"No se encontro puesto de trabajo {ptoId}");
                return View("Index", ObtenerReservas(ptoId, semanaIdx));
            }
            if (!this.ValidarReserva(reserva, ptoId))
            {
                ModelState.AddModelError("", $"Puesto ya esta reservado para ese bloque");
                return View("Index", ObtenerReservas(ptoId, semanaIdx));
            }

            _context.Agendas.Add(new Agenda()
            {
                PuestoTrabajo = puestoTrabajo,
                HoraDesde = reserva.HoraDesde,
                HoraHasta = reserva.HoraHasta,
                FechaReserva = reserva.fecha,
                Artista = artista
            });
            await _context.SaveChangesAsync();
            ViewBag.ShowSuccessMsg = "Y";
        }
        return View("Index", ObtenerReservas(ptoId, semanaIdx));
    }
    [Authorize]
    public IActionResult Actualizar(int id, int ptoId)
    {
        try
        {
            Agenda? agenda = _context.Agendas.Include(art => art.Artista)
                                            .AsNoTracking()
                                            .FirstOrDefault(x => x.Id == id);
            if (agenda == null)
            {
                ModelState.AddModelError("", "Agenda no encontrada");
                return View(new Agenda());
            }
            if (User.Identity == null || User.Identity.Name != agenda.Artista.UserName)
            {
                ModelState.AddModelError("", "Usuario no logeado o distinto a usuario agenda"); ;
                return View(new Agenda());
            }
            return View(agenda);
        }
        finally
        {
            ViewBag.ptoId = ptoId;
            ViewBag.User = User.Identity == null ? "" : User.Identity.Name;
        }
    }
    [HttpGet]
    [Authorize(Roles = "Artista")]
    public async Task<IActionResult> Eliminar(int id, int ptoId)
    {
        try
        {
            if (ModelState.IsValid)
            {
                Agenda? agenda = _context.Agendas.Include(art => art.Artista)
                                        .FirstOrDefault(x => x.Id == id);
                if (agenda == null)
                    ModelState.AddModelError("", "Agenda no encontrada");

                else if (User.Identity == null || User.Identity.Name != agenda.Artista.UserName)
                    ModelState.AddModelError("", "Usuario no logeado o distinto a usuario agenda");
                else
                {
                    _context.Remove(agenda);
                    await _context.SaveChangesAsync();
                    ViewBag.ShowSuccessMsg = "Y";
                }
            }
            return View("Actualizar", new Agenda());
        }
        finally
        {
            ViewBag.ptoId = ptoId;
            ViewBag.User = User.Identity == null ? "" : User.Identity.Name;
        }
    }

    [HttpGet]
    [Authorize(Roles = "Admin")]
    public IActionResult Listar(DateTime? fechaini = null, DateTime? fechafin = null)
    {
        if (fechaini == null)
            fechaini = DateTime.Now.Date;
        if (fechafin == null)
            fechafin = fechaini;

        ViewBag.fechaini = (fechaini ?? DateTime.Now.Date).ToString("yyyy-MM-dd");
        ViewBag.fechafin = (fechafin ?? DateTime.Now.Date).ToString("yyyy-MM-dd");

        return View(_context.Agendas.Where(w => w.FechaReserva >= fechaini && w.FechaReserva <= fechafin)
                                    .Include(art => art.Artista)
                                    .Include(pto => pto.PuestoTrabajo)
                                    .Select(x => new Reserva
                                    {
                                        AgendaId = x.Id,
                                        ArtistaId = x.Artista.Id,
                                        ArtistaUserName = x.Artista.UserName,
                                        PuestoTrabajoId = x.PuestoTrabajo.Id,
                                        FechaReserva = x.FechaReserva,
                                        Bloque = new Bloque() { HoraDesde = x.HoraDesde, HoraHasta = x.HoraHasta }
                                    })
                                    .OrderBy(o => o.FechaReserva)
                                    .ThenBy(o => o.Bloque.HoraDesde)
                                    .ToList());

    }
    private List<Reserva> ObtenerReservas(int ptoId, int semanaIdx)
    {

        List<Reserva> reservas = new List<Reserva>();
        DateTime hoy = semanaIdx == 0 ? DateTime.Now.Date : DateTime.Now.Date.AddDays(semanaIdx * 7);
        List<Bloque> bloques = _context.Bloques.ToList();
        DateTime domingo = hoy.DayOfWeek == DayOfWeek.Sunday ? hoy : hoy.AddDays(7 - (int)hoy.DayOfWeek);//obtiene domingo
        DateTime diaInicio = hoy.AddDays(hoy.DayOfWeek == DayOfWeek.Sunday ? -6 : (1 - (int)hoy.DayOfWeek)); //obtiene lunes

        while ((domingo.Date - diaInicio.Date).Days >= 0)
        {
            //Crea agendas vacias para bloques sin reserva 
            foreach (Bloque bloque in bloques)
            {
                var agenda = _context.Agendas.Include(pto => pto.PuestoTrabajo)
                                             .Include(art => art.Artista)
                                             .FirstOrDefault(x => x.FechaReserva == diaInicio && x.PuestoTrabajo.Id == ptoId &&
                                                         bloque.HoraDesde >= x.HoraDesde && bloque.HoraDesde < x.HoraHasta);


                if (agenda != null)
                    reservas.Add(new Reserva
                    {
                        Bloque = bloque,
                        FechaReserva = diaInicio,
                        PuestoTrabajoId = ptoId,
                        ArtistaId = agenda.Artista.Id,
                        ArtistaUserName = agenda.Artista.UserName,
                        AgendaId = agenda.Id,
                        isReserva = true,
                        ReservaStr1 = agenda.Artista.UserName,
                        ReservaStr3 = $"Reservado"
                        // ReservaStr2 = agenda.Artista.Instagram
                    });
                else
                    reservas.Add(new Reserva { Bloque = bloque, FechaReserva = diaInicio, PuestoTrabajoId = ptoId });

            }

            diaInicio = diaInicio.AddDays(1);
        }

        ViewBag.bloques = bloques;
        ViewBag.ptoId = ptoId;
        ViewBag.semanaIdx = semanaIdx;
        ViewBag.semanaAntIdx = semanaIdx - 1;
        ViewBag.semanaSigIdx = semanaIdx + 1;
        ViewBag.fechaactual = hoy.ToString("yyyy-MM-dd");
        ViewBag.User = User.Identity == null ? "" : User.Identity.Name;
        return reservas;
    }

    private bool ValidarReserva(CrearReserva reserva, int ptoId)
    {
        List<int> horas = new List<int>();
        foreach (Agenda agenda in _context.Agendas.AsNoTracking().Where(x => x.FechaReserva == reserva.fecha && x.PuestoTrabajo.Id == ptoId))
        {
            for (int i = agenda.HoraDesde; i < agenda.HoraHasta; i++)
                horas.Add(i);
        }

        return !horas.Exists(h => h == reserva.HoraDesde || h == reserva.HoraHasta - 1);
    }
}

Views/Agenda/Actualizar.cshtml
@using TattooStudioBooking.Models
@model Agenda
@{
    ViewData["Title"] = "Modificar agenda";
}
<div class="container pt-4">
    <h5>Modificar agenda</h5>
    <form asp-controller="Agenda" asp-action="Eliminar" asp-route-returnurl="@ViewData["ReturnUrl"]" method="get"
        class="row g-3">
        <input type="hidden" id="Id" name="Id" value="@Model.Id" />
        <input type="hidden" id="ptoId" name="ptoId" value="@ViewBag.ptoId" />                  

        <div class="col-md-12">
            <label for="Usuario" class="form-label">Usuario</label>
            <input type="text" class="form-control" id="Usuario" readonly name="Usuario" value="@ViewBag.User">
        </div>
        <div class="col-md-6">
            <label for="HoraDesde" class="form-label">Desde</label>
            <input type="text" class="form-control" id="HoraDesde" readonly name="HoraDesde" value="@Model.HoraDesde">
        </div>
        <div class="col-md-6">
            <label for="HoraHasta" class="form-label">Hasta</label>
            <input type="text" class="form-control" id="HoraHasta" readonly name="HoraHasta" value="@Model.HoraHasta">
        </div>
        <div class="col-4">            
            <a class="btn btn-primary" asp-area="" asp-controller="Agenda" asp-action="Index" asp-route-ptoId="@ViewBag.ptoId">Volver</a>
        </div>
        <div class="col-4">
            <button type="button" disabled class="btn btn-primary">Modificar</button>
        </div>
        <div class="col-4">
            <button type="submit" @(Model.Id == 0 ? "disabled" : "") class="btn btn-primary">Eliminar</button>
        </div>
    </form>
</div>

Views/Agenda/Index.cshtml
@using TattooStudioBooking.Models
@model List<Reserva>
@{
    ViewData["Title"] = "Agenda";
}

<div class="row mb-3">
    <h2>
        @string.Format("Agenda semana del {0} al {1}",
        (Model.OrderBy(x => x.FechaReserva).FirstOrDefault() ?? new Reserva()).FechaReserva.ToString("dd-MM"),
        (Model.OrderByDescending(x => x.FechaReserva).FirstOrDefault() ?? new Reserva()).FechaReserva.ToString("dd-MM"))
    </h2>
    <div class="col-6 text-start">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalReserva">
            Crear Reserva
        </button>
    </div>
    <div class="col-3 text-end">
        <a class="btn btn-secondary" role="button" asp-area="" asp-controller="Agenda" asp-action="Index"
           asp-route-ptoId="@ViewBag.ptoId" asp-route-semanaIdx="@ViewBag.semanaAntIdx">Semana anterior</a>
    </div>
    <div class="col-3 text-start">
        <a class="btn btn-secondary" role="button" asp-area="" asp-controller="Agenda" asp-action="Index"
           asp-route-ptoId="@ViewBag.ptoId" asp-route-semanaIdx="@ViewBag.semanaSigIdx">Semana siguiente</a>
    </div>
</div>
<div class="row">
    <div class="table-responsive">
        @* https://www.bootdey.com/snippets/view/time-table *@
        <table class="table table-bordered text-center">
            <thead>
                <tr class="bg-light-gray">
                    <th class="text-uppercase">Hora</th>
                    <th class="text-uppercase">Lunes</th>
                    <th class="text-uppercase">Martes</th>
                    <th class="text-uppercase">Miercoles</th>
                    <th class="text-uppercase">Jueves</th>
                    <th class="text-uppercase">Viernes</th>
                    <th class="text-uppercase">Sabado</th>
                    <th class="text-uppercase">Domingo</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Bloque bloque in @ViewBag.bloques)
                {
                    <tr>
                        <td class="align-middle">
                            @string.Format("{0}:00",bloque.HoraDesdeStr)
                        </td>
                        @foreach (Reserva reserva in Model.Where(x => x.Bloque.Id == bloque.Id).OrderBy(x => x.FechaReserva))
                        {
                            @if (reserva.isReserva)
                            {
                                <td>
                                    <span class="@string.Format("reserva-span {0} text-white font-size16 xs-font-size13", reserva.ColorReserva.ToString())">
                                        @reserva.ReservaStr1
                                    </span>
                                    <div class="margin-10px-top font-size14">@reserva.ReservaStr2</div>
                                    @if (ViewBag.User == reserva.ArtistaUserName)
                                    {
                                        <div class="font-size13">
                                            @*<a href="@string.Format("/Agenda/Actualizar?Id={0}&ptoId={1}", reserva.AgendaId, ViewBag.ptoId)">*@
                                            <a asp-area="" asp-controller="Agenda" asp-action="Actualizar" asp-route-id="@reserva.AgendaId"
                                               asp-route-ptoId="@ViewBag.ptoId">
                                                Actualizar
                                            </a>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="font-size13 text-light-gray">@reserva.ReservaStr3</div>
                                    }
                                </td>
                            }
                            else
                            {
                                <td class="disponible"></td>
                            }
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@* MODAL REGISTRA AGENDA *@
<div class="modal fade" id="modalReserva" tabindex="-1" aria-labelledby="reservaModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="reservaModalLabel">Reserva agenda</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-controller="Agenda" id="formReserva" asp-action="RegistrarAgenda" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="row g-3">
                    <input type="hidden" id="ptoId" name="ptoId" value="@ViewBag.ptoId" />
                    <input type="hidden" id="semanaIdx" name="semanaIdx" value="@ViewBag.semanaIdx" />
                    <div class="col-md-12">
                        <label for="Usuario" class="form-label">Usuario</label>
                        <input type="text" class="form-control" id="Usuario" readonly name="reserva.Usuario" value="@ViewBag.User">
                    </div>
                    <div class="col-md-12">
                        <label for="fecha">Fecha</label>
                        <input id="fecha" class="form-control" type="date" name="reserva.fecha" value="@ViewBag.fechaactual" placeholder="dd-mm-yyyy" />
                    </div>
                    <div class="col-md-6">
                        <label for="HoraDesde" class="form-label">Desde</label>
                        <select class="form-select" id="HoraDesde" name="reserva.HoraDesde" aria-label="" Default select example"">
                            <option selected>Seleccione</option>
                            @foreach (Bloque bloque in @ViewBag.bloques)
                            {
                                <option value="@bloque.HoraDesde">@(String.Format("{0} - desde las {1}", bloque.Nombre, bloque.HoraDesdeStr))</option>
                            }
                        </select>
                    </div>
                    <div class="col-md-6">
                        <label for="HoraHasta" class="form-label">Hasta</label>
                        <select class="form-select" id="HoraHasta" name="reserva.HoraHasta" aria-label="">
                            <option selected>Seleccione</option>
                            @foreach (Bloque bloque in @ViewBag.bloques)
                            {
                                <option value="@bloque.HoraHasta">@(String.Format("{0} - hasta las {1}", bloque.Nombre, bloque.HoraHastaStr))</option>
                            }
                        </select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="RegistrarAgenda()">Crear reserva</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        //todo https://stackoverflow.com/questions/45428046/changing-input-date-data-type-to-dd-mm-yyyy-instead-of-mm-dd-yyyy-with-require se debe agregar algo de jquery
        //$('#fecha').datepicker({ dateFormat: 'dd-mm-yyyy' }).val();


        RegistrarAgenda = function () {
            $('#modalReserva').modal('hide');

            bootbox.confirm({
                message: '¿Crear reserva?',
                buttons: {
                    confirm: {
                        label: 'Si',
                    },
                    cancel: {
                        label: 'Cancelar',
                    }
                },
                callback: function (result) {
                    if (result) {
                        $('form#formReserva').submit();
                    }
                }
            });
        }
    });
</script>

Views/Agenda/Listar.cshtml
@using TattooStudioBooking.Models
@model List<Reserva>
@{
    ViewData["Title"] = "Lista Agenda";
}

<div class="row g-3 mb-3">
    <form asp-controller="Agenda" id="formListar" asp-action="Listar" method="get" class="row g-3">
        <div class="col-md-6">
            <label for="fechaini">Fecha desde</label>
            <input id="fechaini" class="form-control" type="date" name="fechaini" value="@ViewBag.fechaini"
                placeholder="dd-mm-yyyy" />
        </div>
        <div class="col-md-6">
            <label for="fechafin">Fecha hasta</label>
            <input id="fechafin" class="form-control" type="date" name="fechafin" value="@ViewBag.fechafin"
                placeholder="dd-mm-yyyy" />
        </div>
        <div class="col-md-6">
            <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
    </form>
</div>
<div class="row">
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Id Agenda</th>
                    <th>Id Artista</th>
                    <th>Artista UserName</th>
                    <th>Id Puesto trabajo</th>
                    <th>Fecha Reserva</th>
                    <th>Desde</th>
                    <th>Hasta</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Reserva reserva in Model)

                {
                    <tr>
                        <td>@reserva.AgendaId</td>
                        <td>@reserva.ArtistaId</td>
                        <td>@reserva.ArtistaUserName</td>
                        <td>@reserva.PuestoTrabajoId</td>
                        <td>@reserva.FechaReserva</td>
                        <td>@string.Format("{0}:00", reserva.Bloque.HoraDesdeStr)</td>
                        <td>@string.Format("{0}:00", reserva.Bloque.HoraHastaStr)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>